name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and test frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Build and test backend
      run: |
        cd backend
        npm install